### PR TITLE
Add rules for Diamond (blastp) and Prodigal

### PR DESCRIPTION
**Pull request by zoey-rw**
Four new rules proposed, with no new software dependencies.

1. run_prodigal - predicts ORFs on contigs rather than assembled genomes (perhaps could be renamed to contig_prodigal to avoid confusion)
2. run_blastp - takes contig ORFs as input, uses the Diamond Blastp Snakemake wrapper: https://github.com/snakemake/snakemake-wrappers/tree/0.80.1/bio/diamond/blastp
3. binning - calls the outputs from concoct, metabat, and maxbin
4. binEvaluation - calls the outputs from binRefine and binReassembly

The parsing rules for binning and binEvaluation may be iffy - I tested on a login node, rather than as a cluster job.

### CODE REVIEW

**Comment by franciscozorrilla** [comment]
Thanks @zoey-rw, looks awesome! I will do some small tests and then merge into the main branch 💎

**Review by franciscozorrilla — APPROVED** [review]
💎

**Comment by paristzou** [comment]
After reading the article entitled "The National Ecological Observatory Network’s soil metagenomes: assembly and basic analysis [version 2; peer review: 2 approved with reservations]" (https://f1000research.com/articles/10-299/v2), I hope it can be added soon to benefit more. Thank you so much.

**Comment by paristzou** [comment]
That's great. It makes life much easier.

**Comment by paristzou** [comment]
Is it possible to find a link to have the fastq.gz files for tutorial in https://github.com/franciscozorrilla/unseenbio_metaGEM , please ? Thank you.

**Comment by franciscozorrilla** [comment]
Hi @paristzou, unfortunately that metagenomic data is personal/private and I do not have consent to share it, as it was generated using the [unseen bio](https://unseenbio.com/) metagenome sequencing service. Just to clarify, these particular samples were NOT used in the metaGEM publication/data analysis.

You can find more info about the 5 datasets we used in the metaGEM publication [here](https://github.com/franciscozorrilla/metaGEM_paper).

Additionally, you may find useful the [toy dataset](https://github.com/franciscozorrilla/metaGEM_paper) that we generated by subsampling 3 paired end reads from the gut microbiome dataset.

**Comment by franciscozorrilla** [comment]
I believe that providing the full path to the env directory should do the trick, e.g.

```
source activate /newdisk2/metaGEM/envs/metagem
```

See also the [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#) for a good reference on handling environments and such.
Since this is unrelated to the PR topic, kindly open a new issue if you have further trouble with setup.

**Pull request merged**
